BEGIN{
##############################################################################
##############################################################################
###                                                                        ###
###  Awk script to condition tops file exported from openworks             ###
###  using format "DTE_Tops_Export.wlx" into a form suitable for           ###
###  importing into Zmap for mapping purposes.                             ###
###                                                                        ###
###  For a specific run, from a unix window specify the following:         ###
###                                                                        ###
###        awk -f WellTopFilt.awk < InputFileName > OutputFileName         ###
###                                                                        ###
###             InputFileName: File generated by Well_Data_Export          ###
###                            see notes on how to export tops from        ### 
###                            openworks in file:                          ###
###                                    /home1/expde04/Notes/comp_notes     ###
###                                                                        ###
###             OutputFileName: The file you wish to put results into.     ###
###                             This file will be suitable for importing   ###
###                             into Zmap.                                 ###
###                                                                        ###
##############################################################################
##############################################################################

	#####################################
	#                                   #
	#  You might want to change the     #
	#  following parameters for a       #
	#  particular run.                  #
	#                                   #
	#####################################

        # Number of intial lines to skip
        SkipLines = 10

        # The top name or pick to extract
        DesiredTop = "T50"

	# The interpreter you would like to pick from
        Interpreter = "TEAM"

        # Scalar to applied to depth like -0.3048 to convert
        # ss feet to meters in depth.
	Scale = -1.0


	############################################
	#                                          #
	#  Should be able to leave the rest alone  #
	#                                          #
	############################################

}
{
  if ( NR > SkipLines )
    {
      if ( $1 == "WELL:" )
	{
	  WellName = $2
	  if ( $3 == DesiredTop && $8 == Interpreter )
	    {
	      TopName = $3
	      Xcoord = $6
	      Ycoord = $7
	      Ztvdss = $5 * Scale
	      printf ("%30s %15s %10.2f %10.2f %10.2f\n", WellName, TopName, Xcoord, Ycoord, Ztvdss)
	    }
	}
    }
}
END{}
