BEGIN{
##############################################################################
##############################################################################
###                                                                        ###
###  Awk script to condition tops file exported from openworks             ###
###  using format "DTE_Tops_Export.wlx" into a form                        ###
###  suitable for importing into Zmap for mapping purposes.                ###
###                                                                        ###
###  The program assumes the input file has the following information      ###
###  located in the associated column numbers                              ###
###                                                                        ###
###             Item         Column Number                                 ###
###             _____        _____________                                 ###
###             x-coord            2                                       ###
###             y-coord            3                                       ###
###             tvdss              6                                       ###
###             Interpreter        7                                       ###
###             Top_Name           8                                       ###
###             Well_Name          9                                       ###
###                                                                        ###
###  Columns 3 and 4 are not used but with my format contains MD and TVD.  ###
###  Column 1 is just the number one, and is not used.                     ###
###                                                                        ###
###  For a specific run, from a unix window specify the following:         ###
###                                                                        ###
###        awk -f WellTopFilt.awk < InputFileName > OutputFileName         ###
###                                                                        ###
###             InputFileName: File generated by Well_Data_Export          ###
###                            see notes on how to export tops from        ### 
###                            openworks in file:                          ###
###                                    /home/easleydt/Notes/comp_notes     ###
###                                                                        ###
###             OutputFileName: The file you wish to put results into.     ###
###                             This file will be suitable for importing   ###
###                             into Zmap.                                 ###
###                                                                        ###
##############################################################################
##############################################################################

	#####################################
	#                                   #
	#  You might want to change the     #
	#  following parameters for a       #
	#  particular run.                  #
	#                                   #
	#####################################

        # Number of intial lines to skip.
        SkipLines = 10

        # The top name or pick to extract.
        DesiredTop = "QANTR_MFS"

	# The interpreters you would like to pick from. 
	# The first is given presidence.
        Interpreter1 = "TEAM"
        Interpreter2 = "MVS"

        # Scalar to applied to depth like -0.3048 to convert
        # feet to meters and negative to positive.
	Scale = -1.0


	############################################
	#                                          #
	#  Should be able to leave the rest alone  #
	#                                          #
	############################################
	  
	WellName = "NotAWell_WaxOnWaxOff"
	Case1 = 0
	Case2 = 0
}
{
  if ( NR > SkipLines )
    { 
          if ( WellName != $9 ) 
	    {
	      NoPrint1 = 0
	      NoPrint2 = 0
	      if (Case1 == 1)
		{
		  printf ("%30s %15s %10s %10.2f %10.2f %10.2f\n", WellName1, TopName1, DaMan1, Xcoord1, Ycoord1, Ztvdss1)
		  NoPrint1 = 1
		}
	      if (Case2 == 1 && NoPrint1 == 0)
		{
		  printf ("%30s %15s %10s %10.2f %10.2f %10.2f\n", WellName2, TopName2, DaMan2, Xcoord2, Ycoord2, Ztvdss2)
		  NoPrint2 = 1
		} 
	      Case1 = 0
	      Case2 = 0
	    }
	  WellName = $9
	  if ( $8 == DesiredTop && $7 == Interpreter1 )
	    {
	      if (NF > 9){
		WellName1 = $9
		for (i = 10; i <= NF; i++){
		  WellName1 = WellName1"_"$i
		}
	      }
	      if (NF == 9) WellName1 = $9
	      TopName1 = $8
	      Xcoord1 = $2
	      Ycoord1 = $3
	      Ztvdss1 = $6 * Scale
	      DaMan1 = $7
	      Case1 = 1
	    }
	  if ( $8 == DesiredTop && $7 == Interpreter2 )
	    {
	      if (NF > 9){
		WellName2 = $9
		for (i = 10; i <= NF; i++){
		  WellName2 = WellName2"_"$i
		}
	      }
	      if (NF == 8) WellName2 = $9
	      TopName2 = $8
	      Xcoord2 = $2
	      Ycoord2 = $3
	      Ztvdss2 = $6 * Scale
	      DaMan2 = $7
	      Case2 = 1
	    }
    }
}
END{}
